### ISSUE TITLE
JOSS review: Clean up interface to work in light mode and fit within Notebook

### ISSUE THREAD

**Issue by WarmCyan** [ORNL/icat#45]
As pointed out by @jhagerer in https://github.com/openjournals/joss-reviews/issues/6873#issuecomment-2299852874, the interface doesn't render effectively in a light mode themed Jupyter instance, and is squished within Jupyter Notebook cells (as opposed to Jupyter Lab.)

Copying the example image over here for reference: 
![image](https://github.com/user-attachments/assets/fefef736-c04c-40cf-a174-8164d29e2ebd)

**Comment by jhagerer** [comment]
Hey @WarmCyan , in case to speed up the review process, an easy quick win could also be achieved as follows: Just change the documentation by telling that you need to activate dark theme for Jupyter Lab. You can refer to the following link:

https://stackoverflow.com/a/46219796/776847

**Comment by WarmCyan** [comment]
As it turned out solving the theming issue was much easier than making it fit in Jupyter Notebook. The interface should now be usable in both light-theme and dark-theme Jupyter Lab:
![image](https://github.com/user-attachments/assets/e7196d04-7be2-4f42-9165-66f5c861f5c5)

Note that this required an update to our underlying [ipyanchorviz](https://github.com/ORNL/ipyanchorviz) package, so your environment will need to be updated with `pip install --upgrade ipyanchorviz`

I wasn't able to find a good solution for making it fit correctly inside a Notebook cell -- the space is heavily constrained and there's not an easy way of detecting or overriding this. For now, I'm going to update the documentation to state that this is intended for use only in Jupyter Lab

**Comment by jhagerer** [comment]
I can confirm it is working. You can close the ticket.

**Comment by jhagerer** [comment]
I can confirm that this issue is solved now. Please close.

**Comment by WarmCyan** [comment]
Fitting within a notebook cell has since been fixed in https://github.com/ORNL/icat/commit/5ef3effe10f717150ec52417842c7ecf0181d9b8
