### ISSUE TITLE
JOSS review: include intermediate example notebook

### ISSUE THREAD

**Issue by WarmCyan** [ORNL/icat#46]
Added from @jhagerer https://github.com/openjournals/joss-reviews/issues/6873#issuecomment-2299852874: We go from a trivial "simple_example" notebook that's just expecting default anchors all the way to "lm_similarity_example" which adds a BERT transformer-based anchor (which has quite a few dependencies to get working.) It may be helpful to include an intermediate example that shows adding a custom anchor but doesn't require transformers to work. (word2vec was suggested as a possibility.)

**Comment by jhagerer** [comment]
@WarmCyan I would be happy with any example which does not need cuda/nvidia and gives me as a reviewer more to see and explore than the simple example.

A quick win solution could be to just change [lm_similarity_example.ipynb](https://github.com/ORNL/icat/blob/main/notebooks/lm_similarity_example.ipynb) such that it does not use cuda anymore. How about that?

**Comment by WarmCyan** [comment]
@jhagerer good suggestion, I modified that notebook to first check if cuda is available, and use cpu otherwise.

**Comment by jhagerer** [comment]
OK, I think I have something running now to work with.

Please close the ticket. I'll take some time next weekend to try out and understand the tool more in depth.
